name: pkg-change-broadcast

on:
  push:
    branches: [ ubuntu/focal ]
  pull_request:
    branches: [ ubuntu/focal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Broadcast Event
        run: |
          curl -XPOST -u "${{ secrets.PUBLISH_EVENT_USER}}:${{secrets.PUBLISH_EVENT_KEY}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/regolith-linux/repo-ubuntu-focal/dispatches --data '{"event_type": "package_update"}'
